// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChSvbafjElAWMU7Pa6etgHXvQk0tY1Ib4',
    appId: '1:87382093794:web:f57e0f979aba31259113bb',
    messagingSenderId: '87382093794',
    projectId: 'ornek-fe2c9',
    authDomain: 'ornek-fe2c9.firebaseapp.com',
    storageBucket: 'ornek-fe2c9.firebasestorage.app',
    measurementId: 'G-TTNQ959B53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc_TJ-Ts12zA1mxi700cJhjd-ZdAuFMGM',
    appId: '1:87382093794:android:afa96a5ecd37b18b9113bb',
    messagingSenderId: '87382093794',
    projectId: 'ornek-fe2c9',
    storageBucket: 'ornek-fe2c9.firebasestorage.app',
  );
}
